name: SaludYa CI/CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar lint
        run: npm run lint

      - name: Ejecutar pruebas
        run: npm test

      - name: Build del proyecto
        run: npm run build

  deploy:
    needs: test

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Deploy producción
        run: echo "Desplegando SaludYa..."